export const productCategory = [
  {
      "scategory":"아우터",
      "bcategory":"남성패션의류",
      "bcategory_en":"maleFashion",
      "pcategoryid":1
  },{
      "scategory":"상의",
      "bcategory":"남성패션의류",
      "bcategory_en":"maleFashion",
      "pcategoryid":2
  },{
      "scategory":"하의",
      "bcategory":"남성패션의류",
      "bcategory_en":"maleFashion",
      "pcategoryid":3
  },{
      "scategory":"잠옷/언더웨어",
      "bcategory":"남성패션의류",
      "bcategory_en":"maleFashion",
      "pcategoryid":4
  },{
      "scategory":"정장",
      "bcategory":"남성패션의류",
      "bcategory_en":"maleFashion",
      "pcategoryid":5
  },{
      "scategory":"기타",
      "bcategory":"남성패션의류",
      "bcategory_en":"maleFashion",
      "pcategoryid":6
  },{
      "scategory":"아우터",
      "bcategory":"여성패션의류",
      "bcategory_en":"femaleFashion",
      "pcategoryid":7
  },{
      "scategory":"상의",
      "bcategory":"여성패션의류",
      "bcategory_en":"femaleFashion",
      "pcategoryid":8
  },{
      "scategory":"하의",
      "bcategory":"여성패션의류",
      "bcategory_en":"femaleFashion",
      "pcategoryid":9
  },{
      "scategory":"원피스",
      "bcategory":"여성패션의류",
      "bcategory_en":"femaleFashion",
      "pcategoryid":10
  },{
      "scategory":"잠옷/언더웨어",
      "bcategory":"여성패션의류",
      "bcategory_en":"femaleFashion",
      "pcategoryid":11
  },{
      "scategory":"정장",
      "bcategory":"여성패션의류",
      "bcategory_en":"femaleFashion",
      "pcategoryid":12
  },{
      "scategory":"기타",
      "bcategory":"여성패션의류",
      "bcategory_en":"femaleFashion",
      "pcategoryid":13
  },{
      "scategory":"푸드",
      "bcategory":"반려동물용품",
      "bcategory_en":"pet",
      "pcategoryid":14
  },{
      "scategory":"의류",
      "bcategory":"반려동물용품",
      "bcategory_en":"pet",
      "pcategoryid":15
  },{
      "scategory":"장난감",
      "bcategory":"반려동물용품",
      "bcategory_en":"pet",
      "pcategoryid":16
  },{
      "scategory":"기타",
      "bcategory":"반려동물용품",
      "bcategory_en":"pet",
      "pcategoryid":17
  },{
      "scategory":"농수축산물",
      "bcategory":"푸드/식품",
      "bcategory_en":"food",
      "pcategoryid":18
  },{
      "scategory":"가공식품",
      "bcategory":"푸드/식품",
      "bcategory_en":"food",
      "pcategoryid":19
  },{
      "scategory":"건강식품",
      "bcategory":"푸드/식품",
      "bcategory_en":"food",
      "pcategoryid":20
  },{
      "scategory":"기타",
      "bcategory":"푸드/식품",
      "bcategory_en":"food",
      "pcategoryid":21
  },{
      "scategory":"도서",
      "bcategory":"도서/티켓/교환권",
      "bcategory_en":"bkTckCp",
      "pcategoryid":22
  },{
      "scategory":"티켓",
      "bcategory":"도서/티켓/교환권",
      "bcategory_en":"bkTckCp",
      "pcategoryid":23
  },{
      "scategory":"교환권",
      "bcategory":"도서/티켓/교환권",
      "bcategory_en":"bkTckCp",
      "pcategoryid":24
  },{
      "scategory":"기타",
      "bcategory":"도서/티켓/교환권",
      "bcategory_en":"bkTckCp",
      "pcategoryid":25
  },{
      "scategory":"스포츠웨어",
      "bcategory":"스포츠/레저용품",
      "bcategory_en":"sports",
      "pcategoryid":26
  },{
      "scategory":"수영복",
      "bcategory":"스포츠/레저용품",
      "bcategory_en":"sports",
      "pcategoryid":27
  },{
      "scategory":"헬스/요가/필라테스",
      "bcategory":"스포츠/레저용품",
      "bcategory_en":"sports",
      "pcategoryid":28
  },{
      "scategory":"구기용품",
      "bcategory":"스포츠/레저용품",
      "bcategory_en":"sports",
      "pcategoryid":29
  },{
      "scategory":"자전거/스케이트/킥보드",
      "bcategory":"스포츠/레저용품",
      "bcategory_en":"sports",
      "pcategoryid":30
  },{
      "scategory":"기타",
      "bcategory":"스포츠/레저용품",
      "bcategory_en":"sports",
      "pcategoryid":31
  },{
      "scategory":"향수/디퓨저",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":32
  },{
      "scategory":"스킨케어",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":33
  },{
      "scategory":"바디케어",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":34
  },{
      "scategory":"베이스메이크업",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":35
  },{
      "scategory":"색조메이크업",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":36
  },{
      "scategory":"클렌징",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":37
  },{
      "scategory":"미용소품",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":38
  },{
      "scategory":"헤어용품",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":39
  },{
      "scategory":"네일케어",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":40
  },{
      "scategory":"남성용품",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":41
  },{
      "scategory":"기타",
      "bcategory":"뷰티/미용",
      "bcategory_en":"beauty",
      "pcategoryid":42
  },{
      "scategory":"신발",
      "bcategory":"패션잡화",
      "bcategory_en":"fashionGoods",
      "pcategoryid":43
  },{
      "scategory":"가방/지갑",
      "bcategory":"패션잡화",
      "bcategory_en":"fashionGoods",
      "pcategoryid":44
  },{
      "scategory":"액세서리",
      "bcategory":"패션잡화",
      "bcategory_en":"fashionGoods",
      "pcategoryid":45
  },{
      "scategory":"기타",
      "bcategory":"패션잡화",
      "bcategory_en":"fashionGoods",
      "pcategoryid":46
  },{
      "scategory":"침구",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":47
  },{
      "scategory":"책상/식탁",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":48
  },{
      "scategory":"화장대",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":49
  },{
      "scategory":"의자",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":50
  },{
      "scategory":"소파",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":51
  },{
      "scategory":"선반",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":52
  },{
      "scategory":"서랍/수납장",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":53
  },{
      "scategory":"행거/옷장",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":54
  },{
      "scategory":"거실장",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":55
  },{
      "scategory":"유아동가구",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":56
  },{
      "scategory":"인테리어소품",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":57
  },{
      "scategory":"원예",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":58
  },{
      "scategory":"기타",
      "bcategory":"가구/인테리어",
      "bcategory_en":"interior",
      "pcategoryid":59
  },{
      "scategory":"냉장고",
      "bcategory":"생활가전",
      "bcategory_en":"homeAppliances",
      "pcategoryid":60
  },{
      "scategory":"세탁기/건조기",
      "bcategory":"생활가전",
      "bcategory_en":"homeAppliances",
      "pcategoryid":61
  },{
      "scategory":"TV",
      "bcategory":"생활가전",
      "bcategory_en":"homeAppliances",
      "pcategoryid":62
  },{
      "scategory":"에어컨",
      "bcategory":"생활가전",
      "bcategory_en":"homeAppliances",
      "pcategoryid":63
  },{
      "scategory":"주방가전",
      "bcategory":"생활가전",
      "bcategory_en":"homeAppliances",
      "pcategoryid":64
  },{
      "scategory":"생활/건강가전",
      "bcategory":"생활가전",
      "bcategory_en":"homeAppliances",
      "pcategoryid":65
  },{
      "scategory":"미용가전",
      "bcategory":"생활가전",
      "bcategory_en":"homeAppliances",
      "pcategoryid":66
  },{
      "scategory":"기타",
      "bcategory":"생활가전",
      "bcategory_en":"homeAppliances",
      "pcategoryid":67
  },{
      "scategory":"핸드폰",
      "bcategory":"디지털기기",
      "bcategory_en":"digital",
      "pcategoryid":68
  },{
      "scategory":"태블릿",
      "bcategory":"디지털기기",
      "bcategory_en":"digital",
      "pcategoryid":69
  },{
      "scategory":"웨어러블",
      "bcategory":"디지털기기",
      "bcategory_en":"digital",
      "pcategoryid":70
  },{
      "scategory":"PC/노트북/모니터",
      "bcategory":"디지털기기",
      "bcategory_en":"digital",
      "pcategoryid":71
  },{
      "scategory":"프린터/복합기",
      "bcategory":"디지털기기",
      "bcategory_en":"digital",
      "pcategoryid":72
  },{
      "scategory":"음향기기",
      "bcategory":"디지털기기",
      "bcategory_en":"digital",
      "pcategoryid":73
  },{
      "scategory":"기타",
      "bcategory":"디지털기기",
      "bcategory_en":"digital",
      "pcategoryid":74
  },{
      "scategory":"게임",
      "bcategory":"취미",
      "bcategory_en":"hobby",
      "pcategoryid":75
  },{
      "scategory":"음반/악기",
      "bcategory":"취미",
      "bcategory_en":"hobby",
      "pcategoryid":76
  },{
      "scategory":"장난감/완구/교구",
      "bcategory":"취미",
      "bcategory_en":"hobby",
      "pcategoryid":77
  },{
      "scategory":"기타",
      "bcategory":"취미",
      "bcategory_en":"hobby",
      "pcategoryid":78
  },{
      "scategory":"기타",
      "bcategory":"기타",
      "bcategory_en":"etc",
      "pcategoryid":79
  },
  
]